/*
 This file contains all constants in the app.
 */
module.exports = {
    // ACTION TYPES
    AIM_AT: "AIM_AT",
    KILL_HERO: "KILL_HERO",
    RESET: "RESET",
    DUCK_DOWN: "DUCK_DOWN",
    STAND_UP: "STAND_UP",

    // HERO STATUSES
    AIMING: "AIMING",
    DUCKING: "DUCKING",
    WAITING: "WAITING",
    DEAD: "DEAD",

    CONTACT_ADDED: "CONTACT_ADDED",
    CONTACT_REMOVED: "CONTACT_REMOVED",
    CONTACT_BEGIN_EDIT: "CONTACT_BEGIN_EDIT",
    CONTACT_END_EDIT: "CONTACT_END_EDIT",
    CONTACT_EDITED: "CONTACT_EDITED",
    CONTACT_SAVED: "CONTACT_SAVED",

    LOADED_FROM_LOCALSTORAGE: "LOADED_FROM_LOCALSTORAGE",
    LOCALSTORAGE_KEY: "CONTACTAPP_KEY",

    CHAT_MESSAGE: "CHAT_MESSAGE",
    ECHO_CHAT_MESSAGE: "ECHO_CHAT_MESSAGE",
    SET_CHAT_NAME: "SET_CHAT_NAME"
};