/*
 This file contains all constants in the app.
 */
export default {
    CONTACT_ADDED: "CONTACT_ADDED",
    CONTACT_REMOVED: "CONTACT_REMOVED",
    CONTACT_BEGIN_EDIT: "CONTACT_BEGIN_EDIT",
    CONTACT_END_EDIT: "CONTACT_END_EDIT",
    CONTACT_EDITED: "CONTACT_EDITED",
    CONTACT_SAVED: "CONTACT_SAVED",
    CONTACT_BEGIN_ADD: "CONTACT_BEGIN_ADD",
    CONTACT_END_ADD: "CONTACT_END_ADD",

    CHAT_MESSAGE: "CHAT_MESSAGE",
    ECHO_CHAT_MESSAGE: "ECHO_CHAT_MESSAGE",
    SET_CHAT_NAME: "SET_CHAT_NAME",
    SAVE_MESSAGES: "SAVE_MESSAGES",
    MESSAGES_NOT_FORMATTED_CORRECTLY: "MESSAGES_NOT_FORMATTED_CORRECTLY"
};